# Tip: You might need to modify the port value on the 
# localhost URL when debugging in Visual Studio.

GET http://localhost:7071/api/httpget HTTP/1.1

###

GET http://localhost:7071/api/httpget?name=World HTTP/1.1

###

POST http://localhost:7071/api/httppost HTTP/1.1
content-type: application/json

{
    "name": "Awesome Developer",
    "age": 25
}
